/**
 * Taxonomy codes aligned with docs/TAXONOMY.md.
 * Maps EventCategory and source context to taxonomy codes.
 */

export const TAXONOMY_CODES = [
  'security.strike',
  'security.exchange',
  'security.assassination',
  'security.border',
  'security.military',
  'security.explosion',
  'security.kidnapping',
  'security.cyber',
  'security.outage',
  'politics.government',
  'politics.parliament',
  'politics.party',
  'politics.nomination',
  'politics.negotiation',
  'politics.reform',
  'politics.corruption',
  'politics.justice',
  'politics.diplomacy',
  'economy.currency',
  'economy.inflation',
  'economy.bank',
  'economy.energy',
  'economy.commerce',
  'economy.investment',
  'economy.sanctions',
  'economy.employment',
  'economy.transport',
  'society.displacement',
  'society.aid',
  'society.health',
  'society.education',
  'society.ngo',
  'society.cohesion',
  'society.crisis',
  'environment.fire',
  'environment.earthquake',
  'environment.pollution',
  'environment.weather',
  'environment.water',
  'environment.disaster',
  'culture.event',
  'culture.heritage',
  'culture.festival',
  'culture.university',
  'culture.startup',
  'culture.sport',
] as const;

export type TaxonomyCode = (typeof TAXONOMY_CODES)[number];

/** Maps legacy EventCategory to taxonomy codes. */
export const CATEGORY_TO_TAXONOMY: Record<string, TaxonomyCode> = {
  armed_conflict: 'security.military',
  economic_crisis: 'economy.inflation',
  political_tension: 'politics.party',
  displacement: 'society.displacement',
  infrastructure_failure: 'security.outage',
  environmental_negative: 'environment.pollution',
  disinformation: 'politics.corruption',
  violence: 'security.strike',
  cultural_event: 'culture.event',
  reconstruction: 'politics.reform',
  institutional_progress: 'politics.government',
  solidarity: 'society.cohesion',
  economic_positive: 'economy.investment',
  international_recognition: 'politics.diplomacy',
  environmental_positive: 'environment.water',
  neutral: 'culture.event',
};
